package com.fauzi.wings.core.model;

public enum Permission {
    VIEW_ADMIN_DASHBOARD,
    VIEW_EXECUTIVE_DASHBOARD,
    VIEW_MANAGER_DASHBOARD,
    VIEW_SUPERVISOR_DASHBOARD,
    VIEW_STAFF_DASHBOARD,
    MANAGE_USERS,
    CREATE_REQUEST,
    VIEW_REQUESTS,
    VIEW_DEPARTMENT_REQUESTS,
    VIEW_ALL_REQUESTS,
    APPROVE_LEVEL_1,
    APPROVE_LEVEL_2,
    APPROVE_LEVEL_3,
    VIEW_ANALYTICS,
    VIEW_TEAM_ANALYTICS,
    EXPORT_AUDIT,
    EXPORT_CHART,
    IMPERSONATE,
    SYNC_DATA,
    FORCE_ESCALATE
}
